import Head from 'next/head';
import Header from '../components/Header'
import Banner from '../components/Banner';
import BannerBg from '@/assets/banner.png';


export default function Home() {
  return (
    <>
      <Head>
        <title>The Frontend Freaks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Banner src={BannerBg} />
        <h1 className="mt-8 text-2xl md:text-5xl text-center">Frontend Developer Essential Course!</h1>
      </main>
    </>
  )
}
